# Generated by Django 2.2.4 on 2020-12-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audio',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
