# Generated by Django 2.2.4 on 2020-12-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_book_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(to='APP.Book'),
        ),
    ]
