# Generated by Django 2.2.4 on 2020-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_explore_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.CharField(max_length=225)),
            ],
        ),
    ]
