# Generated by Django 2.2.4 on 2020-12-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_bookmar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookmar',
            new_name='Bookmark',
        ),
    ]
