# Generated by Django 2.2.4 on 2020-12-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_auto_20201214_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('authors_image', models.ImageField(upload_to='')),
                ('authors_email', models.TextField()),
                ('cover_image', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('audio', models.FileField(upload_to='')),
                ('link', models.CharField(max_length=225)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
